name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-22.04
    steps:
      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2.2.1
        with:
          github_user_name: mahmoudbassuoni
          outputs: dist/snake.svg
      # Push the animation to GitHub Pages
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
