name: Generate Snake Animation
on:
  schedule: # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2.2.1
        with:
          github_user_name: mahmoudbassuoni

      # Ensure the output branch exists
      - name: Create Output Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan output || git switch output
          git reset --hard
          git commit --allow-empty -m "Initial commit for output branch"
          git push origin output

      # Push the animation to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
